source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-assetpack'
gem 'rake'
gem 'mongo'
gem 'bson_ext'
gem 'byebug'
gem 'octokit'
gem 'compass'
gem 'foundation'
gem 'shotgun'